---
title: "Dossiê Americana"
---

---

O que é Americana? Quem são os americanenses ? Como e onde vivem? Do que se alimentam?

Brincadeiras a parte, questões simples como estas nos ajudam a pensar a cidade, o povo que vive nela, as dinâmicas sociais, as questões ambientais, econômicas e  a partir desta compreensão, buscar respostas para os problemas que afligem o povo.

Não podemos esquecer que uma cidade não é uma ilha, logo, ela está sujeita aos resultados das políticas praticadas nas cidades vizinhas, e nas esferas dos governos estaduais, federais, e das políticas internacionais.

O foco deste dossiê não é contar a história da cidade _ o que seria muito bonito _ mas é mostrar informações relevantes para colaborar com a campanha para as eleições municipais de 2020. Portanto, infelizmente, não espere encontrar aqui poesias, hinos, fatos curiosos ou histórias antigas dessa bela cidade. O documento, em apoio com outros materiais, visa apresentar a cidade em dados, que servirão como informações para tomada de decisões para a criação de propostas para a apreciação da população americanense _ e podemos pensar que ele pode servir para além destas eleições, e ajudar em projetos futuros.

Esse documento não tem uma versão final, sendo assim, ele pode e deve continuar a ser modificado, até que se encontre o máximo ideal possível.

Conhecer uma cidade razoavelmente grande, com tantas pessoas, não é uma tarefa das mais simples. Portanto, vamos apresentar a cidade aos poucos, começando por uma análise mais geral, depois partindo para uma análise física (geográfica), do próprio espaço do município, depois iniciaremos uma análise do povo americanense, passando claro, por análises eleitorais, e finalmente partiremos para análises mais específicas, algo mais relacionado aos indicadores de gestão urbana.

---

